# Generated by Django 6.0.6 on 2026-06-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('izoh', models.CharField(max_length=245)),
                ('janr', models.CharField(max_length=245)),
                ('yili', models.DateField()),
                ('rasm', models.ImageField(upload_to='')),
            ],
        ),
    ]
